# Generated by Django 5.2.3 on 2025-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(default=0),
        ),
    ]
